package firstpromoter

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

type TrackSaleInput struct {
	// ID of the lead added on signup tracking. Required if email is not provided.
	Uid *string
	// Email of the lead/sign-up. Required if uid is not provided.
	Email *string
	// Transaction or sale event ID. Required to avoid duplicate sales.
	EventId string
	// The sale amount in cents. For zero-decimal currencies like JPY, amount should be whole values.
	Amount int
	// Number of subscriptions/items. Optional if quantity is 1.
	Quantity *int
	// Customer plan ID from billing provider. Used for plan-level rewards.
	Plan *string
	// Required only if different from FirstPromoter settings default currency.
	Currency *string
	// Monthly Recurring Revenue generated by the customer.
	Mrr *string
	// For promo code tracking.
	PromoCode *string
	// Visitor tracking ID from _fprom_tid cookie.
	Tid *string
	// Referral ID of the promoter.
	RefId *string
	// Set true to skip email notifications. Default is false.
	SkipEmailNotification *bool
}

type TrackSaleOutput struct {
	Id                   int
	Etype                string
	SaleAmount           *int
	OriginalSaleAmount   *int
	OriginalSaleCurrency *string
	EventId              *string
	PlanId               *string
	BillingPeriod        *string
	CreatedAt            time.Time
	Referral             Referral
}

func (client Client) TrackSale(ctx context.Context, input TrackSaleInput) (*TrackSaleOutput, error) {
	var reqBody struct {
		Uid                   string `json:"uid,omitempty"`
		Email                 string `json:"email,omitempty"`
		EventId               string `json:"event_id"`
		Amount                int    `json:"amount"`
		Quantity              int    `json:"quantity,omitempty"`
		Plan                  string `json:"plan,omitempty"`
		Currency              string `json:"currency,omitempty"`
		Mrr                   string `json:"mrr,omitempty"`
		PromoCode             string `json:"promo_code,omitempty"`
		Tid                   string `json:"tid,omitempty"`
		RefId                 string `json:"ref_id,omitempty"`
		SkipEmailNotification bool   `json:"skip_email_notification"`
	}

	if input.Uid != nil {
		reqBody.Uid = *input.Uid
	}

	if input.Email != nil {
		reqBody.Email = *input.Email
	}

	reqBody.EventId = input.EventId
	reqBody.Amount = input.Amount

	if input.Quantity != nil {
		reqBody.Quantity = *input.Quantity
	}

	if input.Plan != nil {
		reqBody.Plan = *input.Plan
	}

	if input.Currency != nil {
		reqBody.Currency = *input.Currency
	}

	if input.Mrr != nil {
		reqBody.Mrr = *input.Mrr
	}

	if input.PromoCode != nil {
		reqBody.PromoCode = *input.PromoCode
	}

	if input.Tid != nil {
		reqBody.Tid = *input.Tid
	}

	if input.RefId != nil {
		reqBody.RefId = *input.RefId
	}

	if input.SkipEmailNotification != nil {
		reqBody.SkipEmailNotification = *input.SkipEmailNotification
	}

	reqBodyBytes, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("marshal signup request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, "https://v2.firstpromoter.com/api/v2/track/sale", bytes.NewReader(reqBodyBytes))
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Account-ID", client.accountId)
	req.Header.Set("Authorization", "Bearer "+client.apiKey)

	resp, err := client.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		slurp, _ := io.ReadAll(io.LimitReader(resp.Body, 8<<10))
		return nil, fmt.Errorf("signup: unexpected status %s: %s", resp.Status, string(slurp))
	}

	var respBody struct {
		Id                   int      `json:"id"`
		Etype                string   `json:"etype"`
		SaleAmount           *int     `json:"sale_amount"`
		OriginalSaleAmount   *int     `json:"original_sale_amount"`
		OriginalSaleCurrency *string  `json:"original_sale_currency"`
		EventId              *string  `json:"event_id"`
		PlanId               *string  `json:"plan_id"`
		BillingPeriod        *string  `json:"billing_period"`
		CreatedAt            string   `json:"created_at"`
		Referral             Referral `json:"referral"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&respBody); err != nil && err != io.EOF {
		return nil, fmt.Errorf("decode response: %w", err)
	}

	createdAt, err := time.Parse(time.RFC3339, respBody.CreatedAt)
	if err == nil {
		return nil, fmt.Errorf("Error parsing CreatedAt")
	}

	return &TrackSaleOutput{
		Id:                   respBody.Id,
		Etype:                respBody.Etype,
		SaleAmount:           respBody.SaleAmount,
		OriginalSaleAmount:   respBody.OriginalSaleAmount,
		OriginalSaleCurrency: respBody.OriginalSaleCurrency,
		EventId:              respBody.EventId,
		PlanId:               respBody.PlanId,
		BillingPeriod:        respBody.BillingPeriod,
		CreatedAt:            createdAt,
		Referral:             respBody.Referral,
	}, nil
}
